### PR TITLE
add Trident/8.0 IE11 variant

### PR DESCRIPTION
**Pull request by actsasflinn**
Cover an additional IE11 Trident engine that I am seeing in the wild.

### CODE REVIEW

**Comment by kuraga** [comment]
@gshutler what's issue here?

**Comment by actsasflinn** [comment]
Trident 8 is another variant of IE11 which is not detected by useragent. This patch adds support.

**Comment by gshutler** [comment]
Sorry, I think I missed the notification for it or something.

**Comment by gshutler** [comment]
Released in version 0.16.4

**Pull request merged**
