### PR TITLE
Media player support

### PR DESCRIPTION
**Pull request by gshutler**
Noticed this whilst looking at the network graph and it looks worth pulling in to the gem.

### CODE REVIEW

**Comment by gshutler** [comment]
@ziggythehamster have you been using your fork yourself? Would you be happy for them to be incorporated into the official gem?

The changes look pretty good from a skim and would also resolve josh/useragent#84

**Comment by gshutler** [comment]
I've made a branch that resolves the merge conflict with master https://github.com/gshutler/useragent/tree/pr/1 so this is good to merge as far as I'm concerned.

**Comment by ziggythehamster** [comment]
We aren't using it in production yet, and there are more media players we need to parse, but the tests pass :-). So yes, feel free to merge this. When we parse more media players, we can make a PR to include those.

Of particular note, I've done a ton of independent research on Windows Media Player, so that is probably the most helpful of all of these changes. The main reason was I wanted to rule out the UA that ffmpeg uses as being legit (it isn't).

**Comment by gshutler** [comment]
Awesome, thanks for all your hard work.

This may also help with josh/useragent#95

**Pull request merged**
